module.exports = {
  '   ┌───┐    \n   │   ┼┐   \n   ├────┼┼  ': 'Bandana',
  '   ┌┬┬┬┬┐   \n   ╓┬┬┬┬╖   \n   ╙┴┴┴┴╜   ': 'Beanie',
  '   ╒════╕   \n  ┌┴────┴┐  \n  └┬────┬┘  ': 'Trilby',
  '   ╒════╕   \n   │□□□□│   \n  └┬────┬┘  ': 'Bowler',
  '   ╒════╕   \n   │    │   \n └─┬────┬─┘ ': 'Cowboy',
  '    ◙◙◙◙    \n   ▄████▄   \n   ┌────┐   ': 'Tophat',
  '   ┌───┐    \n┌──┤   └┐   \n└──┼────┤   ': 'Forwards baseball cap',
  '    ┌───┐   \n   ┌┘   ├──┐\n   ├────┼──┘': 'Backwards baseball cap',
  '   ┌────┐/  \n┌──┴────┴──┐\n└──┬────┬──┘': 'Cavalier',
  '   ╒════╕   \n ┌─┴────┴─┐ \n └─┬────┬─┘ ': 'Gambler',
  '  ┌──────┐  \n  │▲▲▲▲▲▲│  \n  └┬────┬┘  ': 'Cossack',
  '  ┌┌────┐┐  \n  ││┌──┐││  \n  └┼┴──┴┼┘  ': 'Ushanka',
  '   ┌────┐   \n  ┌┘─   │   \n  └┌────┐   ': 'Forwards beret',
  '            \n   ┌┬┬┬┬┐   \n   ├┴┴┴┴┤   ': 'Flat top',
  '            \n    ╓┬╥┐    \n   ┌╨┴╨┴┐   ': 'Peak spike',
  '            \n   ╒╦╦╦╦╕   \n   ╞╩╩╩╩╡   ': 'Kufi',
  '            \n            \n   ┌┼┼┼┼┐   ': 'Short spike',
  '            \n    ││││    \n   ┌┼┼┼┼┐   ': 'Long spike',
  '      ╔     \n     ╔║     \n   ┌─╫╫─┐   ': 'Mohawk',
  '            \n    ║║║║    \n   ┌╨╨╨╨┐   ': 'Long thick spike',
  '            \n   ▐▐▐▌▌▌   \n   ┌────┐   ': 'Wide spike',
  '            \n   \\/////   \n   ┌────┐   ': 'Electrified',
  '    ┐ ┌     \n   ┐││││┌   \n   ┌────┐   ': 'Bed head',
  '  ┌┐ ┐┌┐┌┐  \n  └└┐││┌┘   \n   ┌┴┴┴┴┐   ': 'Frazzled',
  '  ┐┐┐┐┐     \n  └└└└└┐    \n   └└└└└┐   ': 'Front spike',
  '            \n   ││││││   \n   ┌────┐   ': 'Thin spike',
  '            \n    ╓╓╓╓    \n   ┌╨╨╨╨┐   ': 'Slicked back',
  '    ╔╔╗╗╗   \n   ╔╔╔╗╗╗╗  \n  ╔╝╝║ ╚╚╗  ': 'Curls',
  '   ╔╔╔╔╔╗   \n  ╔╔╔╔╔╗║╗  \n  ╝║╨╨╨╨║╚  ': 'Thick curls',
  '   ╔╔═╔═╔   \n   ╔╩╔╩╔╝   \n   ┌────┐   ': 'Beach head',
  '            \n     ///    \n   ┌────┐   ': 'Balding',
  '     ╔╗╔╗   \n    ╔╗╔╗╝   \n   ┌╔╝╔╝┐   ': 'Curly mohawk',
  '     ╔╔╔╔╝  \n    ╔╝╔╝    \n   ┌╨╨╨─┐   ': 'Rat tail',
  '       ╔╗   \n    ╔╔╔╗╝   \n   ┌╚╚╝╝┐   ': 'Man bun',
  '   ╔════╗   \n  ╔╚╚╚╝╝╝╗  \n  ╟┌────┐╢  ': 'Helmet',
  '    ╔═╗     \n    ╚╚╚╗    \n   ┌────┐   ': 'Armstrong',
  '            \n            \n   ┌╨╨╨╨┐   ': 'Buzz cut',
  '            \n    ⌂⌂⌂⌂    \n   ┌────┐   ': 'Demon crown',
  '   ┌────┐   \n   │   /└┐  \n   ├────┐/  ': 'Backwards beret',
  '            \n   ((((((   \n   ┌────┐   ': 'Wavy',
  '   ┌┌┌┌┌┐   \n   ├┘┘┘┘┘   \n   ┌────┐   ': 'Pompador',
  '   «°┐      \n    │╪╕     \n   ┌└┼──┐   ': 'Parrot top',
  "  <° °>   § \n   \\'/   /  \n   {())}}   \n": 'Snake charmer',
  '   ██████   \n  ██ ██ ██  \n █ ██████ █ ': 'Space invader',
  '    ████    \n   ██◙◙██   \n   ┌─▼▼─┐   ': 'Brain parasite',
  '   ╓╖  ╓╖   \n  °╜╚╗╔╝╙°  \n   ┌─╨╨─┐   ': 'Court jester',
  '   ± ±± ±   \n   ◙◙◙◙◙◙   \n   ┌────┐   ': 'Crown',
  '  ♫     ♪   \n    ♪     ♫ \n ♪ ┌────┐   ': 'Musician',
  '    /≡≡\\    \n   /≡≡≡≡\\   \n  /┌────┐\\  ': 'Rice',
  '            \n   ♣♥♦♠♣♥   \n   ┌────┐   ': 'Two pair',
  '     [⌂]    \n      │     \n   ┌────┐   ': 'Robot',
  '  /\\/\\/\\/\\  \n  \\\\/\\/\\//  \n   ┌────┐   ': 'Basket',
  '    ↑↑↓↓    \n   ←→←→AB   \n   ┌────┐   ': 'Komani code',
  '    ┌─┬┐    \n   ┌┘┌┘└┐   \n   ├─┴──┤   ': 'Tetris',
  '    ☼  ☼    \n     \\/     \n   ┌────┐   ': 'Alien',
}
