module.exports = {
  '   │    │   \n   │──  │   ': 'Unimpressed',
  '   │    │   \n   │δ   │   ': 'Kissy',
  '   │    │   \n   │─┬  │   ': 'Drooling',
  '   │    │   \n   │(─) │   ': 'Grizzled',
  '   │    │   \n   │[─] │   ': 'Hardened',
  '   │    │   \n   │<─> │   ': 'Pursed lips',
  '   │    │   \n   │╙─  │   ': 'Smirk left',
  '   │    │   \n   │─╜  │   ': 'Smirk right',
  '   │    │   \n   │└─┘ │   ': 'Happy',
  '   │    │   \n   │┌─┐ │   ': 'Pissed',
  '   │    │   \n   │╓─  │   ': 'Frown left',
  '   │    │   \n   │─╖  │   ': 'Frown right',
  '   │    │   \n   │┼─┼ │   ': 'Undead',
  '   │    │   \n   │──┼ │   ': 'Split lip',
  '   │    │   \n   │«─» │   ': 'Pursed lips 2',
  ' ∙ │    │   \n ∙───   │   ': 'Cigarette',
  ' ∙ │    │   \n ∙───)  │   ': 'Joint',
  ' ∙ │    │   \n ∙───]  │   ': 'Cigar',
  '   │⌐¬  │   \n √────  │   ': 'Pipe',
  '   │╓╖  │   \n   │──  │   ': 'Thick moustache',
  '   │~~  │   \n   │/\\  │   ': 'Pencil moustache',
  '   │    │   \n   │══  │   ': 'Juicy lips',
  '   │    │   \n   │▼▼  │   ': 'Fangs',
  '   │⌐¬  │   \n   │O   │   ': 'Surprised',
  '   │    │   \n   │O   │   ': 'Surprised',
  ' ∙ │⌐¬  │   \n ∙───   │   ': 'Cigarette',
  ' ∙ │⌐¬  │   \n ∙───)  │   ': 'Joint',
  ' ∙ │⌐¬  │   \n ∙───]  │   ': 'Cigar',
  '   │⌐¬  │   \n   │──  │   ': 'Unimpressed',
  '   │⌐-¬ │   \n   │    │   ': 'French',
  '   │┌-┐ │   \n   ││ │ │   ': 'Fu Manchu',
}
